version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    working_directory: ~/shopperholics

    steps:
      - checkout
      - run:
          name: install testing dependencies
          command: |
            sudo pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            pytest --cov .
            
      - run:
          name: send coverage data to coveralls
          command: |
            coveralls


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
